### ISSUE TITLE
Create presentation

### ISSUE THREAD

**Issue by toni-kolev** [SoftUniTestBlog/SoftUniBlog#4]
Create a PPT/PPTX presentation.

We have 15 minutes to present the following:

1. Code commit triggers build in TeamCity (should be done by Toni)
2. Add a new test to framework (coordinate with QA team who will be doing a live presentation)
3. Explain how each team member has contributed: display the commit logs in the Source Control system you have been using.

Please be strict in timing! On the 15th minute you will be interrupted! It is good idea to leave the last 2-3 minutes for questions from the other students, trainers and assistants.

Be well prepared for presenting maximum of your work for minimum time. Bring your own laptop. Test it preliminary with the multimedia projector. Open the project assets beforehand to save time.

**Comment by bboshnakov** [comment]
Done.
